# Generated by Django 5.1.6 on 2025-03-05 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_vacancy_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Job Category',
                'verbose_name_plural': 'Job Categories',
            },
        ),
        migrations.RemoveField(
            model_name='resume',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='keywords',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='Is Processed'),
        ),
        migrations.CreateModel(
            name='AnalysisKeyRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('job_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_requirements', to='core.jobcategory')),
            ],
            options={
                'verbose_name': 'Analysis Key Requirement',
                'verbose_name_plural': 'Analysis Key Requirements',
                'unique_together': {('name', 'job_category')},
            },
        ),
        migrations.CreateModel(
            name='JobSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='core.jobcategory')),
            ],
            options={
                'verbose_name': 'Job Subcategory',
                'verbose_name_plural': 'Job Subcategories',
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='VacancyAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('work_format', models.CharField(blank=True, max_length=50, null=True)),
                ('salary_range_min', models.CharField(blank=True, max_length=50, null=True)),
                ('salary_range_max', models.CharField(blank=True, max_length=50, null=True)),
                ('salary_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('experience_years_required', models.CharField(blank=True, max_length=10, null=True)),
                ('job_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.jobcategory')),
                ('job_subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.jobsubcategory')),
                ('key_requirements', models.ManyToManyField(blank=True, related_name='vacancies_data', to='core.analysiskeyrequirement')),
                ('vacancy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='core.vacancy')),
            ],
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
    ]
